commit_message: "Crowdin: Update %language% messages [ci skip]"
append_commit_message: false
preserve_hierarchy: true
export_languages:
  - cs
  - de
  - es-ES
  - fr
  - id
  - it
  - ja
  - ko
  - nl
  - pl
  - pt-BR
  - ru
  - uk
  - vi
  - zh-CN
  - zh-TW
  - tr
  - fi
  - th
files:
  - source: /common/src/main/resources/messages/messages_en.yml
    translation: /common/src/main/resources/messages/messages_%two_letters_code%.yml
    dest: /%file_name%.yml
    skip_untranslated_strings: true