files:
  - source: /common/src/main/resources/messages/messages_en.yml
    translation: /common/src/main/resources/messages/messages_%two_letters_code%.yml
    skip_untranslated_files: true
    skip_untranslated_strings: true