# +-----------------------------------------------------------------------------+ #
# |                        Aurelium Skills Ability Config                       | #
# |     Abilities Guide: https://wiki.aurelium.dev/skills/config/abilities      | #
# +-----------------------------------------------------------------------------+ #

abilities:
  farming:
    bountiful_harvest:
      enabled: true
      base: 10.0
      per_level: 5.0
      unlock: 2
      level_up: 5
      max_level: 0
    farmer:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    scythe_master:
      enabled: true
      base: 3.0
      per_level: 2.0
      unlock: 4
      level_up: 5
      max_level: 0
    geneticist:
      enabled: true
      base: 1.0
      per_level: 2.0
      unlock: 5
      level_up: 5
      max_level: 0
    triple_harvest:
      enabled: true
      base: 5.0
      per_level: 3.0
      unlock: 6
      level_up: 5
      max_level: 0
  foraging:
    lumberjack:
      enabled: true
      base: 10.0
      per_level: 5.0
      unlock: 2
      level_up: 5
      max_level: 0
    forager:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    axe_master:
      enabled: true
      base: 4.0
      per_level: 3.0
      unlock: 4
      level_up: 5
      max_level: 0
    valor:
      enabled: true
      base: 1.0
      per_level: 1.0
      unlock: 5
      level_up: 5
      max_level: 0
    shredder:
      enabled: true
      base: 3.0
      per_level: 3.0
      unlock: 6
      level_up: 5
      max_level: 0
  mining:
    lucky_miner:
      enabled: true
      base: 3.0
      per_level: 3.0
      unlock: 2
      level_up: 5
      max_level: 0
    miner:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    pick_master:
      enabled: true
      base: 3.0
      per_level: 2.0
      unlock: 4
      level_up: 5
      max_level: 0
    stamina:
      enabled: true
      base: 1.0
      per_level: 1.0
      unlock: 5
      level_up: 5
      max_level: 0
    hardened_armor:
      enabled: true
      base: 3.0
      per_level: 3.0
      unlock: 6
      level_up: 5
      max_level: 0
  fishing:
    lucky_catch:
      enabled: true
      base: 10.0
      per_level: 5.0
      unlock: 2
      level_up: 5
      max_level: 0
    fisher:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    treasure_hunter:
      enabled: true
      base: 1.0
      per_level: 1.0
      unlock: 4
      level_up: 5
      max_level: 0
      scale_base_chance: false
    grappler:
      enabled: true
      base: 50.0
      per_level: 100.0
      unlock: 5
      level_up: 5
      max_level: 0
    epic_catch:
      enabled: true
      base: 0.4
      per_level: 0.4
      unlock: 6
      level_up: 5
      max_level: 0
      scale_base_chance: false
  excavation:
    metal_detector:
      enabled: true
      base: 0.5
      per_level: 0.4
      unlock: 2
      level_up: 5
      max_level: 0
      scale_base_chance: false
    excavator:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    spade_master:
      enabled: true
      base: 3.0
      per_level: 2.0
      unlock: 4
      level_up: 5
      max_level: 0
    bigger_scoop:
      enabled: true
      base: 3.0
      per_level: 3.0
      unlock: 5
      level_up: 5
      max_level: 0
    lucky_spades:
      enabled: true
      base: 0.1
      per_level: 0.05
      unlock: 6
      level_up: 5
      max_level: 0
      scale_base_chance: false
  archery:
    crit_chance:
      enabled: true
      base: 5.0
      per_level: 5.0
      unlock: 2
      level_up: 5
      max_level: 0
    archer:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    bow_master:
      enabled: true
      base: 3.0
      per_level: 2.0
      unlock: 4
      level_up: 5
      max_level: 0
    piercing:
      enabled: true
      base: 3.0
      per_level: 3.0
      unlock: 5
      level_up: 5
      max_level: 0
    stun:
      enabled: true
      base: 2.0
      per_level: 1.0
      unlock: 6
      level_up: 5
      max_level: 0
  defense:
    shielding:
      enabled: true
      base: 2.0
      per_level: 3.0
      unlock: 2
      level_up: 5
      max_level: 0
    defender:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    mob_master:
      enabled: true
      base: 2.0
      per_level: 3.0
      unlock: 4
      level_up: 5
      max_level: 0
    immunity:
      enabled: true
      base: 0.5
      per_level: 0.4
      unlock: 5
      level_up: 5
      max_level: 0
    no_debuff:
      enabled: true
      base: 5.0
      per_level: 5.0
      unlock: 6
      level_up: 5
      max_level: 0
  fighting:
    crit_damage:
      enabled: true
      base: 5.0
      per_level: 3.0
      unlock: 2
      level_up: 5
      max_level: 0
    fighter:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    sword_master:
      enabled: true
      base: 3.0
      per_level: 2.0
      unlock: 4
      level_up: 5
      max_level: 0
    first_strike:
      enabled: true
      base: 20.0
      per_level: 8.0
      unlock: 5
      level_up: 5
      max_level: 0
      enable_message: true
      cooldown_ticks: 6000
    bleed:
      enabled: true
      base: 3.0
      per_level: 3.0
      base_2: 0.5
      per_level_2: 0.5
      unlock: 6
      level_up: 5
      max_level: 0
      enable_enemy_message: true
      enable_self_message: true
      enable_stop_message: true
      base_ticks: 3
      added_ticks: 2
      max_ticks: 11
      tick_period: 40
      show_particles: true
  endurance:
    anti_hunger:
      enabled: true
      base: 5.0
      per_level: 5.0
      unlock: 2
      level_up: 5
      max_level: 0
    runner:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    golden_heal:
      enabled: true
      base: 5.0
      per_level: 6.0
      unlock: 4
      level_up: 5
      max_level: 0
    recovery:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 5
      level_up: 5
      max_level: 0
    meal_steal:
      enabled: true
      base: 1.0
      per_level: 2.0
      unlock: 6
      level_up: 5
      max_level: 0
  agility:
    light_fall:
      enabled: true
      base: 2.0
      per_level: 1.5
      unlock: 2
      level_up: 5
      max_level: 0
    jumper:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    sugar_rush:
      enabled: true
      base: 5.0
      per_level: 7.0
      unlock: 4
      level_up: 5
      max_level: 0
    fleeting:
      enabled: true
      base: 5.0
      per_level: 4.0
      unlock: 5
      level_up: 5
      max_level: 0
      health_percent_required: 20.0
    thunder_fall:
      enabled: true
      base: 3.0
      per_level: 2.0
      base_2: 10.0
      per_level_2: 5.0
      unlock: 6
      level_up: 5
      max_level: 0
  alchemy:
    alchemist:
      enabled: true
      base: 3.0
      per_level: 4.0
      unlock: 2
      level_up: 5
      max_level: 0
      add_item_lore: true
    brewer:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    splasher:
      enabled: true
      base: 0.5
      per_level: 0.25
      unlock: 4
      level_up: 5
      max_level: 0
    lingering:
      enabled: true
      base: 5.0
      per_level: 4.0
      base_2: 3.0
      per_level_2: 2.0
      unlock: 5
      level_up: 5
      max_level: 0
    wise_effect:
      enabled: true
      base: 1.0
      per_level: 1.0
      unlock: 6
      level_up: 5
      max_level: 0
  enchanting:
    xp_convert:
      enabled: true
      base: 20.0
      per_level: -0.75
      unlock: 2
      level_up: 5
      max_level: 0
    enchanter:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    xp_warrior:
      enabled: true
      base: 5.0
      per_level: 4.0
      unlock: 4
      level_up: 5
      max_level: 0
    enchanted_strength:
      enabled: true
      base: 0.5
      per_level: 0.5
      unlock: 5
      level_up: 5
      max_level: 0
    lucky_table:
      enabled: true
      base: 5.0
      per_level: 1.0
      unlock: 6
      level_up: 5
      max_level: 0
  healing:
    life_essence:
      enabled: true
      base: 10.0
      per_level: 7.0
      unlock: 2
      level_up: 5
      max_level: 0
    healer:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    life_steal:
      enabled: true
      base: 2.5
      per_level: 1.0
      unlock: 4
      level_up: 5
      max_level: 0
    golden_heart:
      enabled: true
      base: 5.0
      per_level: 3.0
      unlock: 5
      level_up: 5
      max_level: 0
    revival:
      enabled: true
      base: 5.0
      per_level: 4.0
      base_2: 7.0
      per_level_2: 6.0
      unlock: 6
      level_up: 5
      max_level: 0
      enable_message: true
  forging:
    disenchanter:
      enabled: true
      base: 10.0
      per_level: 7.0
      unlock: 2
      level_up: 5
      max_level: 0
    forger:
      enabled: true
      base: 10.0
      per_level: 10.0
      unlock: 3
      level_up: 5
      max_level: 0
    repairing:
      enabled: true
      base: 5.0
      per_level: 4.0
      unlock: 4
      level_up: 5
      max_level: 0
    anvil_master:
      enabled: true
      base: 43.0
      per_level: 3.0
      unlock: 5
      level_up: 5
      max_level: 0
    skill_mender:
      enabled: true
      base: 2.0
      per_level: 1.0
      unlock: 6
      level_up: 5
      max_level: 0
mana_abilities:
  replenish:
    enabled: true
    base_value: 5.0
    value_per_level: 5.0
    cooldown: 200
    cooldown_per_level: -5
    mana_cost: 20
    mana_cost_per_level: 20
    unlock: 7
    level_up: 7
    max_level: 0
    require_sneak: false
    check_offhand: true
    sneak_offhand_bypass: true
    replant_delay: 4
    show_particles: true
    prevent_unripe_break: true
  treecapitator:
    enabled: true
    base_value: 5.0
    value_per_level: 5.0
    cooldown: 200
    cooldown_per_level: -5
    mana_cost: 20
    mana_cost_per_level: 20
    unlock: 7
    level_up: 7
    max_level: 0
    require_sneak: false
    check_offhand: true
    sneak_offhand_bypass: true
    max_blocks_multiplier: 1
  speed_mine:
    enabled: true
    base_value: 5.0
    value_per_level: 5.0
    cooldown: 200
    cooldown_per_level: -5
    mana_cost: 20
    mana_cost_per_level: 20
    unlock: 7
    level_up: 7
    max_level: 0
    require_sneak: false
    check_offhand: true
    sneak_offhand_bypass: true
    haste_level: 10
  sharp_hook:
    enabled: true
    base_value: 0.5
    value_per_level: 0.5
    cooldown: 2
    cooldown_per_level: -0.1
    mana_cost: 5
    mana_cost_per_level: 2
    unlock: 7
    level_up: 7
    max_level: 0
    display_damage_with_scaling: true
    enable_sound: true
    disable_health_check: false
  terraform:
    enabled: true
    base_value: 5.0
    value_per_level: 4.0
    cooldown: 200
    cooldown_per_level: -5
    mana_cost: 20
    mana_cost_per_level: 20
    unlock: 7
    level_up: 7
    max_level: 0
    require_sneak: false
    check_offhand: true
    sneak_offhand_bypass: true
    max_blocks: 61
  charged_shot:
    enabled: true
    base_value: 0.5
    value_per_level: 0.3
    cooldown: 0
    cooldown_per_level: 0
    mana_cost: 5
    mana_cost_per_level: 5
    unlock: 7
    level_up: 7
    max_level: 0
    enable_message: true
    enable_sound: true
  absorption:
    enabled: true
    base_value: 2.0
    value_per_level: 3.0
    cooldown: 200
    cooldown_per_level: -5
    mana_cost: 10
    mana_cost_per_level: 10
    unlock: 7
    level_up: 7
    max_level: 0
    enable_particles: true
  lightning_blade:
    enabled: true
    base_value: 5.0
    value_per_level: 5.0
    cooldown: 200
    cooldown_per_level: -5
    mana_cost: 20
    mana_cost_per_level: 20
    base_duration: 5.0
    duration_per_level: 4.0
    unlock: 7
    level_up: 7
    max_level: 0
    require_sneak: false
    check_offhand: true
    sneak_offhand_bypass: true
file_version: 13
