# +----------------------------------------------------------------------------+ #
# |                       Aurelium Skills Configuration                        | #
# |                                                                            | #
# |                    Discord: https://discord.gg/Bh2EZfB                     | #
# |            Source Code: https://github.com/Archy-X/AureliumSkills          | #
# |      Config Guide: https://wiki.aurelium.dev/skills/config/main-config     | #
# +----------------------------------------------------------------------------+ #
# Plugin made by Archy

# MySql Options
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: auraskills
  username: root
  password: pass
  load_delay: 0
  always_load_on_join: false
  ssl: false

hooks:
  HolographicDisplays:
    enabled: false
  DecentHolograms:
    enabled: true
  LuckPerms:
    enabled: true
  PlaceholderAPI:
    enabled: true
  ProtocolLib:
    enabled: true
  Slimefun:
    enabled: true
  Towny:
    enabled: true
  Vault:
    enabled: true
  WorldGuard:
    enabled: true
    blocked_regions:
      - 'Example'
    blocked_check_replace_regions:
      - 'Example'

default_language: en

try_detect_client_language: false

languages:
  - en
  - es
  - id
  - fr
  - zh-TW
  - tr
  - pl
  - pt-BR
  - zh-CN
  - de
  - lt
  - ru
  - it
  - ko
  - cs
  - nl
  - ja

# Action Bar Options
action_bar:
  enabled: true
  idle: true
  ability: true
  xp: false
  maxed: false
  update_period: 5
  round_xp: false
  placeholder_api: true
  use_suffix: true

# Boss Bar Options
boss_bar:
  enabled: true
  mode: single
  stay_time: 60
  update_every: 1
  round_xp: false
  display_maxed: true
  placeholder_api: true
  use_suffix: true
  format:
    - 'FARMING GREEN PROGRESS'
    - 'FORAGING RED PROGRESS'
    - 'MINING PURPLE PROGRESS'
    - 'FISHING BLUE PROGRESS'
    - 'EXCAVATION YELLOW PROGRESS'
    - 'ARCHERY PINK PROGRESS'
    - 'DEFENSE BLUE PROGRESS'
    - 'FIGHTING RED PROGRESS'
    - 'ENDURANCE PURPLE PROGRESS'
    - 'AGILITY WHITE PROGRESS'
    - 'ALCHEMY PINK PROGRESS'
    - 'ENCHANTING PURPLE PROGRESS'
    - 'SORCERY BLUE PROGRESS'
    - 'HEALING WHITE PROGRESS'
    - 'FORGING YELLOW PROGRESS'

# The base mana amount
base_mana: 20

# Whether certain numbers should show up as roman numerals:
enable_roman_numerals: true

damage_holograms:
  enabled: true
  scaling: true
  decimal:
    display_when_less_than: 1
    max_amount: 1
  offset:
    x: 0
    y: 0
    z: 0
    random:
      enabled: false
      x_min: -0.5
      x_max: 0.5
      y_min: 0
      y_max: 0
      z_min: -0.5
      z_max: 0.5
  colors:
    default: gray
    critical:
      digits: [gray, white, yellow, gold, red, dark_red, dark_purple, light_purple, blue, dark_blue]

leaderboards:
  update_period: 6000
  update_delay: 6000

# Skill Options
enable_skill_commands: true

check_block_replace: true
blocked_check_block_replace_worlds:
  - Example
blocked_check_block_replace_regions:
  - Example

blocked_worlds:
  - Example

blocked_regions:
  - spawn

disabled_worlds:
  - Example

disable_in_creative_mode: false
reset_skills_on_death: false
reset_xp_on_death: false

auto_save:
  enabled: false
  interval_ticks: 12000

skill_money_rewards:
  enabled: false
  base: 100
  multiplier: 10

leveler:
  title:
    enabled: true
    fade_in: 5
    stay: 100
    fade_out: 5
  sound:
    enabled: true
    type: ENTITY_PLAYER_LEVELUP
    category: MASTER
    volume: 1.0
    pitch: 0.5
  double_check_delay: 20

modifier:
  armor:
    equip_blocked_materials:
      - EXAMPLE
    timer:
      enabled: false
      check_period: 3
  item:
    check_period: 3
    enable_off_hand: true
  multiplier:
    enabled: true
  auto_convert_from_legacy: true

requirement:
  enabled: true
  item:
    prevent_tool_use: true
    prevent_weapon_use: true
    prevent_block_place: true
    prevent_interact: true
    global:
  armor:
    prevent_armor_equip: true
    global:

critical:
  base_multiplier: 1.5
  enabled:
    sword: true
    bow: true
    axe: true
    pickaxe: true
    shovel: true
    hoe: true
    hand: false
    other: false

menus:
  placeholder_api: true

check_for_updates: true

automatic_backups:
  enabled: true
  minimum_interval_hours: 24

save_blank_profiles: false