sources:
  farming:
    wheat: 2.0
    potato: 2.5
    carrot: 2.7
    beetroot: 3.0
    nether_wart: 3.0
    pumpkin: 3.4
    melon: 3.4
    sugar_cane: 1.7
    bamboo: 0.25
    cocoa: 4.0
    cactus: 6.0
    brown_mushroom: 7.0
    red_mushroom: 7.0
    kelp: 0.3
    sea_pickle: 4.0
    sweet_berry_bush: 2.5
    glow_berries: 4.5
    torchflower: 9.0
    pitcher_plant: 10.0
  foraging:
    oak_log: 4.0
    spruce_log: 4.0
    birch_log: 4.0
    jungle_log: 4.0
    acacia_log: 4.0
    dark_oak_log: 4.0
    mangrove_log: 4.0
    cherry_log: 4.0
    oak_leaves: 0.4
    spruce_leaves: 0.4
    birch_leaves: 0.4
    jungle_leaves: 0.4
    acacia_leaves: 0.4
    dark_oak_leaves: 0.4
    mangrove_leaves: 0.4
    cherry_leaves: 0.4
    crimson_stem: 5.0
    warped_stem: 5.0
    nether_wart_block: 0.5
    warped_wart_block: 0.5
    moss_block: 3.2
    moss_carpet: 0.2
    azalea: 7.0
    flowering_azalea: 9.1
    azalea_leaves: 1.5
    flowering_azalea_leaves: 2.0
    mangrove_roots: 2.0
    pink_petals: 0.2
  mining:
    stone: 0.2
    cobblestone: 0.2
    andesite: 0.2
    diorite: 0.2
    granite: 0.2
    coal_ore: 1.0
    nether_quartz_ore: 1.8
    iron_ore: 1.8
    lapis_ore: 30.6
    redstone_ore: 5.9
    gold_ore: 17.8
    diamond_ore: 47.3
    emerald_ore: 100.0
    terracotta: 0.5
    white_terracotta: 0.5
    orange_terracotta: 0.5
    yellow_terracotta: 0.5
    light_gray_terracotta: 0.5
    brown_terracotta: 0.5
    red_terracotta: 0.5
    netherrack: 0.1
    blackstone: 0.3
    basalt: 0.4
    magma_block: 0.7
    nether_gold_ore: 10.0
    ancient_debris: 500.0
    end_stone: 0.5
    obsidian: 10.0
    deepslate: 0.4
    copper_ore: 3.5
    tuff: 0.5
    calcite: 0.8
    smooth_basalt: 0.8
    amethyst_block: 4.0
    amethyst_cluster: 6.0
    deepslate_coal_ore: 1.2
    deepslate_iron_ore: 2.2
    deepslate_copper_ore: 4.2
    deepslate_gold_ore: 21.4
    deepslate_redstone_ore: 7.1
    deepslate_lapis_ore: 36.7
    deepslate_emerald_ore: 120.0
    deepslate_diamond_ore: 56.8
    dripstone_block: 3.2
    ice: 0.3
    packed_ice: 0.8
    blue_ice: 1.3
    reinforced_deepslate: 125.0
  fishing:
    cod: 25.0
    salmon: 60.0
    tropical_fish: 750.0
    pufferfish: 115.0
    treasure: 1000.0
    junk: 30.0
    rare: 2000.0
    epic: 5000.0
  excavation:
    dirt: 0.3
    grass_block: 0.7
    sand: 0.4
    gravel: 1.5
    mycelium: 3.7
    clay: 2.4
    soul_sand: 2.7
    coarse_dirt: 2.3
    podzol: 2.5
    soul_soil: 3.0
    red_sand: 0.7
    rooted_dirt: 5.6
    mud: 0.5
    muddy_mangrove_roots: 2.5
  archery:
    player: 50.0
    bat: 1.0
    cat: 1.0
    chicken: 1.0
    cod: 1.0
    cow: 2.0
    donkey: 2.0
    fox: 3.0
    giant: 10.0
    horse: 2.0
    mooshroom: 2.0
    mule: 2.0
    ocelot: 1.0
    parrot: 1.0
    pig: 2.0
    rabbit: 1.0
    salmon: 1.0
    sheep: 2.0
    skeleton_horse: 3.0
    snow_golem: 3.0
    squid: 2.0
    strider: 3.0
    tropical_fish: 1.0
    turtle: 2.0
    villager: 2.0
    wandering_trader: 2.0
    bee: 3.0
    cave_spider: 5.0
    dolphin: 3.0
    enderman: 7.0
    iron_golem: 17.0
    llama: 4.0
    piglin: 5.0
    panda: 5.0
    polar_bear: 7.0
    pufferfish: 1.0
    spider: 5.0
    wolf: 4.0
    zombified_piglin: 4.0
    blaze: 10.0
    creeper: 10.0
    drowned: 7.0
    elder_guardian: 100.0
    endermite: 5.0
    evoker: 35.0
    ghast: 17.0
    guardian: 15.0
    hoglin: 12.0
    husk: 7.0
    illusioner: 17.0
    magma_cube: 12.0
    phantom: 10.0
    piglin_brute: 35.0
    pillager: 12.0
    ravager: 100.0
    shulker: 15.0
    silverfish: 5.0
    skeleton: 7.0
    slime: 5.0
    stray: 8.0
    vex: 10.0
    vindicator: 12.0
    witch: 9.0
    wither_skeleton: 17.0
    zoglin: 12.0
    zombie: 7.0
    zombie_villager: 7.0
    ender_dragon: 7000.0
    wither: 7000.0
    axolotl: 3.5
    glow_squid: 2.5
    goat: 3.0
    allay: 0.2
    frog: 2.0
    tadpole: 0.7
    warden: 10000.0
    camel: 3.0
    sniffer: 3.0
  defense:
    mob_damage: 1
    player_damage: 2
  fighting:
    player: 50.0
    bat: 1.0
    cat: 1.0
    chicken: 1.0
    cod: 1.0
    cow: 2.0
    donkey: 2.0
    fox: 3.0
    giant: 10.0
    horse: 2.0
    mooshroom: 2.0
    mule: 2.0
    ocelot: 1.0
    parrot: 1.0
    pig: 2.0
    rabbit: 1.0
    salmon: 1.0
    sheep: 2.0
    skeleton_horse: 3.0
    snow_golem: 3.0
    squid: 2.0
    strider: 3.0
    tropical_fish: 1.0
    turtle: 2.0
    villager: 2.0
    wandering_trader: 2.0
    bee: 3.0
    cave_spider: 5.0
    dolphin: 3.0
    enderman: 7.0
    iron_golem: 17.0
    llama: 4.0
    piglin: 5.0
    panda: 5.0
    polar_bear: 7.0
    pufferfish: 1.0
    spider: 5.0
    wolf: 4.0
    zombified_piglin: 4.0
    blaze: 10.0
    creeper: 10.0
    drowned: 7.0
    elder_guardian: 100.0
    endermite: 5.0
    evoker: 35.0
    ghast: 17.0
    guardian: 15.0
    hoglin: 12.0
    husk: 7.0
    illusioner: 17.0
    magma_cube: 12.0
    phantom: 10.0
    piglin_brute: 35.0
    pillager: 12.0
    ravager: 100.0
    shulker: 15.0
    silverfish: 5.0
    skeleton: 7.0
    slime: 5.0
    stray: 8.0
    vex: 10.0
    vindicator: 12.0
    witch: 9.0
    wither_skeleton: 17.0
    zoglin: 12.0
    zombie: 7.0
    zombie_villager: 7.0
    ender_dragon: 7000.0
    wither: 7000.0
    axolotl: 3.5
    glow_squid: 2.5
    goat: 3.0
    allay: 0.2
    frog: 2.0
    tadpole: 1.2
    warden: 10000.0
    camel: 3.0
    sniffer: 3.0
  endurance:
    walk_per_meter: 0.333
    sprint_per_meter: 0.1
    swim_per_meter: 1
  agility:
    jump_per_100: 10
    fall_damage: 2
  alchemy:
    awkward: 10
    regular: 15
    extended: 25
    upgraded: 25
    splash: 35
    lingering: 50
  enchanting:
    weapon_per_level: 2
    armor_per_level: 2
    tool_per_level: 2
    book_per_level: 2
  sorcery:
    mana_ability_use: 0.5
    sculk: 1.0
    sculk_catalyst: 12.0
    sculk_shrieker: 27.0
    sculk_vein: 0.5
    sculk_sensor: 8.0
  healing:
    drink_regular: 10
    drink_extended: 15
    drink_upgraded: 15
    splash_regular: 20
    splash_extended: 25
    splash_upgraded: 25
    lingering_regular: 30
    lingering_extended: 35
    lingering_upgraded: 35
    golden_apple: 5
    enchanted_golden_apple: 50
  forging:
    combine_books_per_level: 10
    combine_weapon_per_level: 15
    combine_armor_per_level: 20
    combine_tool_per_level: 25
    grindstone_per_level: 30
tags:
  farming:
    bountiful_harvest_applicable:
      - '*'
    triple_harvest_applicable:
      - '*'
  foraging:
    lumberjack_applicable:
      - '*'
  mining:
    lucky_miner_applicable:
      - coal_ore
      - nether_quartz_ore
      - iron_ore
      - redstone_ore
      - lapis_ore
      - gold_ore
      - diamond_ore
      - emerald_ore
      - nether_gold_ore
      - ancient_debris
      - copper_ore
      - deepslate_coal_ore
      - deepslate_iron_ore
      - deepslate_copper_ore
      - deepslate_gold_ore
      - deepslate_redstone_ore
      - deepslate_lapis_ore
      - deepslate_emerald_ore
      - deepslate_diamond_ore
    speed_mine_applicable:
      - '*'
  excavation:
    dirts:
      - dirt
      - podzol
      - coarse_dirt
      - rooted_dirt
      - mycelium
      - grass_block
    bigger_scoop_applicable:
      - '*'
    metal_detector_applicable:
      - '*'
    lucky_spades_applicable:
      - '*'
    terraform_applicable:
      - '*'
file_version: 9