name: Feature Request
description: Suggest a feature or enhancement
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sharing your ideas. Please note that feature requests are not guaranteed to be added.
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and detailed description of what the feature is and its use case.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false