package dev.aurelium.auraskills.common.storage.sql.dialect;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.SequencedMap;

/**
 * Postgres equivalent of {@link MySqlDialect}. Deliberate differences from the MySQL schema:
 * <ul>
 *     <li>{@code timestamptz} rather than {@code timestamp}, because MySQL's {@code TIMESTAMP}
 *     converts to and from the session time zone while a Postgres {@code timestamp} does not.
 *     Using the plain type would shift {@code log_time} and silently break the
 *     {@code last_updated > ?} leaderboard filter whenever the server and JVM zones differ.</li>
 *     <li>Identity columns are {@code GENERATED BY DEFAULT}, not {@code ALWAYS}, so that rows
 *     carrying an explicit id can still be inserted the way MySQL allows.</li>
 *     <li>{@code modifiers_uk} is a separate expression index, because Postgres has no prefix
 *     indexes and an expression index cannot be an inline table constraint.</li>
 *     <li>Constraint names are prefixed: unlike MySQL, Postgres constraint names are unique per
 *     schema rather than per table, and {@code UUID} is a reserved type name.</li>
 * </ul>
 */
public class PostgresDialect extends AbstractSqlDialect {

    public static final String ID = "postgres";

    @Override
    public String id() {
        return ID;
    }

    @Override
    public SequencedMap<String, List<String>> tableDefinitions(String prefix) {
        SequencedMap<String, List<String>> tables = new LinkedHashMap<>();

        tables.put("users", List.of("""
                create table %susers (
                    user_id     int generated by default as identity primary key,
                    player_uuid varchar(40) not null,
                    locale      varchar(10) null,
                    mana        double precision not null,
                    constraint %susers_uuid_uk unique (player_uuid)
                )
                """.formatted(prefix, prefix)));

        tables.put("skill_levels", List.of("""
                create table %sskill_levels (
                    user_id     int not null,
                    skill_name  varchar(40) not null,
                    skill_level int not null,
                    skill_xp    double precision not null,
                    primary key (user_id, skill_name),
                    constraint %sskill_levels_user_id_fk
                        foreign key (user_id) references %susers (user_id)
                )
                """.formatted(prefix, prefix, prefix)));

        tables.put("key_values", List.of("""
                create table %skey_values (
                    user_id     int not null,
                    data_id     int not null,
                    category_id varchar(128) null,
                    key_name    varchar(128) not null,
                    value       varchar(512) not null,
                    constraint %skey_values_uk
                        unique (user_id, data_id, category_id, key_name),
                    constraint %skey_values_user_id_fk
                        foreign key (user_id) references %susers (user_id)
                )
                """.formatted(prefix, prefix, prefix, prefix)));

        tables.put("logs", List.of("""
                create table %slogs (
                    log_id        bigint generated by default as identity primary key,
                    log_type      varchar(50)  not null,
                    log_time      timestamptz  not null,
                    log_level     int          null,
                    log_message   text         null,
                    player_uuid   varchar(40)  null,
                    player_coords varchar(100) null,
                    world_name    varchar(100) null,
                    other_data    json         null
                )
                """.formatted(prefix)));

        tables.put("modifiers", List.of("""
                create table %smodifiers (
                    modifier_id        int generated by default as identity primary key,
                    user_id            int          not null,
                    modifier_type      varchar(128) not null,
                    type_id            varchar(512) null,
                    modifier_name      varchar(512) not null,
                    modifier_value     double precision not null,
                    modifier_operation smallint     not null,
                    expiration_time    bigint       null,
                    remaining_duration bigint       null,
                    metadata           text         null,
                    constraint %smodifiers_user_id_fk
                        foreign key (user_id) references %susers (user_id)
                )
                """.formatted(prefix, prefix, prefix),
                // Prefix indexes cannot be table constraints in Postgres, so modifiers_uk is a
                // separate expression index. ON CONFLICT must repeat these expressions verbatim.
                "create unique index %smodifiers_uk on %smodifiers (%s)"
                        .formatted(prefix, prefix, String.join(", ", modifiersConflictTarget()))));

        return tables;
    }

    @Override
    public String migrationsTableDdl(String table) {
        return """
                CREATE TABLE IF NOT EXISTS %s (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    file_name VARCHAR(255) NOT NULL UNIQUE,
                    applied_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                )
                """.formatted(table);
    }

    @Override
    public boolean tableExists(Connection connection, String table) throws SQLException {
        // The Postgres driver ignores the catalog argument, and a null schema pattern searches
        // every schema on the server, so constrain the lookup to the connection's own schema
        return tableExists(connection, null, connection.getSchema(), table);
    }

    @Override
    public String upsert(String table, List<String> columns, List<String> conflictTarget,
                         List<String> updateColumns, Map<String, String> literalUpdates) {
        validate(columns, updateColumns);
        if (conflictTarget.isEmpty()) {
            throw new IllegalArgumentException("Postgres upserts require an explicit conflict target");
        }
        String assignments = assignments(updateColumns, literalUpdates, column -> "EXCLUDED." + column);
        return insertInto(table, columns)
                + " ON CONFLICT (" + String.join(", ", conflictTarget) + ") DO UPDATE SET " + assignments;
    }

    @Override
    public String insertIgnore(String table, List<String> columns) {
        return insertInto(table, columns) + " ON CONFLICT DO NOTHING";
    }

    @Override
    public String jsonArrayAgg() {
        return "json_agg";
    }

    @Override
    public String jsonObject() {
        return "json_build_object";
    }

    @Override
    public String prefixedIndexColumn(String column, int prefixLength) {
        return "left(" + column + ", " + prefixLength + ")";
    }

    @Override
    public String updatedWithinSecondsCondition() {
        return "last_updated > CURRENT_TIMESTAMP - make_interval(secs => ?)";
    }

}
