package com.archyx.aureliumskills.api.event;

public enum LootDropCause {

    BOUNTIFUL_HARVEST,
    TRIPLE_HARVEST,
    LUMBERJACK,
    LUCKY_MINER,
    LUCKY_CATCH,
    TREASURE_HUNTER,
    EPIC_CATCH,
    METAL_DETECTOR,
    BIGGER_SCOOP,
    LUCKY_SPADES,
    LUCK_DOUBLE_DROP,
    FISHING_OTHER_LOOT,
    EXCAVATION_OTHER_LOOT,
    MINING_OTHER_LOOT,
    FORAGING_OTHER_LOOT

}
