package com.archyx.aureliumskills.commands;

public enum Command {
    
    ARMOR_MODIFIER_ADD,
    ARMOR_MODIFIER_REMOVE,
    ARMOR_MODIFIER_LIST,
    ARMOR_MODIFIER_REMOVEALL,
    ITEM_MODIFIER_ADD,
    ITEM_MODIFIER_REMOVE,
    ITEM_MODIFIER_LIST,
    ITEM_MODIFIER_REMOVEALL,
    LANG,
    MODIFIER_ADD,
    MODIFIER_REMOVE,
    MODIFIER_LIST,
    MODIFIER_REMOVEALL,
    RANK,
    RELOAD,
    SAVE,
    SKILL_RESET,
    SKILL_SETALL,
    SKILL_SETLEVEL,
    TOGGLE,
    TOP,
    UPDATELEADERBOARDS,
    XP_ADD,
    XP_SET,
    XP_REMOVE
    
}
