name: Run checkstyle
on:
  pull_request:
permissions:
  contents: read
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up JDK 21
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          java-version: "21"
          distribution: temurin
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb
        with:
          gradle-version: "8.10.2"
      - name: Run checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
